/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rUj5285lUxk
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Footer() {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="bg-black py-6 dark:bg-black">
      <div className="container mx-auto text-center text-sm text-gray-400 dark:text-gray-400">
        $CGS CatGirlSweeney is not affiliated with Sydney Sweeney
      </div>
      <div className="container mx-auto text-center text-sm text-gray-400 dark:text-gray-400">
        but is a tribute to the beloved goddess.
      </div>

      <div className="container mx-auto text-center text-sm text-gray-400 dark:text-gray-400 mt-3">
        Copyright © {currentYear}
      </div>
    </footer>
  );
}
